// import { Job, JobCategory, Application } from "@/types";

// export const MOCK_JOBS: Job[] = [
//   {
//     id: "job-1",
//     title: "Senior Frontend Engineer",
//     department: JobCategory.Engineering,
//     location: "Remote",
//     type: "Full-time",
//     experience: "5+ years",
//     salary: "₹25L - ₹35L",
//     skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
//     description:
//       "We are looking for a Senior Frontend Engineer to lead the development of our core web applications. You will work closely with our design and product teams to build scalable, performant, and beautiful user interfaces.",
//     responsibilities: [
//       "Architect and build scalable frontend applications using Next.js and React.",
//       "Collaborate with cross-functional teams to define, design, and ship new features.",
//       "Ensure the technical feasibility of UI/UX designs.",
//       "Optimize applications for maximum speed and scalability.",
//       "Mentor junior engineers and contribute to our engineering culture.",
//     ],
//     requirements: [
//       "5+ years of experience in frontend development.",
//       "Deep understanding of React, Next.js, and modern JavaScript.",
//       "Experience with state management libraries (e.g., Redux, Zustand) and data fetching (e.g., React Query).",
//       "Strong proficiency in CSS and experience with utility-first frameworks like Tailwind CSS.",
//       "Excellent problem-solving skills and a strong attention to detail.",
//     ],
//     perks: [
//       "Fully remote work environment",
//       "Comprehensive health, dental, and vision insurance",
//       "Unlimited PTO",
//       "Home office stipend",
//       "Annual learning and development budget",
//     ],
//     postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
//     featured: true,
//   },
//   {
//     id: "job-2",
//     title: "Product Designer",
//     department: JobCategory.Design,
//     location: "Bengaluru, KA (Hybrid)",
//     type: "Full-time",
//     experience: "3-5 years",
//     salary: "₹15L - ₹25L",
//     skills: ["Figma", "Prototyping", "UX Research", "Design Systems"],
//     description:
//       "Join us as a Product Designer and help shape the future of our platform. You will be responsible for creating intuitive, beautiful, and accessible user experiences.",
//     responsibilities: [
//       "Lead the design process from concept to execution for new product features.",
//       "Conduct user research and translate insights into actionable design improvements.",
//       "Create wireframes, prototypes, and high-fidelity mockups.",
//       "Maintain and evolve our design system.",
//       "Collaborate closely with engineers to ensure high-quality implementation.",
//     ],
//     requirements: [
//       "3-5 years of product design experience, preferably in B2B SaaS.",
//       "A strong portfolio demonstrating your design process and impact.",
//       "Expertise in Figma and other design tools.",
//       "Experience building and maintaining design systems.",
//       "Strong communication and presentation skills.",
//     ],
//     perks: [
//       "Flexible hybrid work schedule",
//       "Premium health benefits",
//       "Generous equity package",
//       "Regular team offsites and events",
//       "Fitness stipend",
//     ],
//     postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
//     featured: true,
//   },
//   {
//     id: "job-3",
//     title: "Growth Marketing Manager",
//     department: JobCategory.Marketing,
//     location: "Mumbai, MH",
//     type: "Full-time",
//     experience: "4-6 years",
//     salary: "₹18L - ₹28L",
//     skills: ["SEO/SEM", "Performance Marketing", "Data Analysis", "Campaign Management"],
//     description:
//       "We're looking for a data-driven Growth Marketing Manager to scale our user acquisition efforts. You will own the strategy and execution of performance marketing campaigns across multiple channels.",
//     responsibilities: [
//       "Develop and execute strategies to drive user acquisition and revenue growth.",
//       "Manage performance marketing campaigns across paid search, social, and display.",
//       "Analyze campaign performance and optimize for CAC and LTV.",
//       "Collaborate with the creative team to develop high-performing ad copy and assets.",
//       "Conduct A/B testing on landing pages and ad creatives.",
//     ],
//     requirements: [
//       "4-6 years of experience in growth marketing or user acquisition.",
//       "Proven track record of managing and scaling multi-channel paid campaigns.",
//       "Strong analytical skills and experience with tools like Google Analytics, Mixpanel, etc.",
//       "Deep understanding of SEO and SEM best practices.",
//       "Excellent project management and communication skills.",
//     ],
//     perks: [
//       "Competitive salary and equity",
//       "Comprehensive health coverage",
//       "401(k) matching",
//       "Commuter benefits",
//       "Free lunches on Tuesdays and Thursdays",
//     ],
//     postedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days ago
//     featured: true,
//   },
//   {
//     id: "job-4",
//     title: "Backend Engineer",
//     department: JobCategory.Engineering,
//     location: "Remote",
//     type: '"Day" | "Night" | "Flexible"',
//     experience: "3+ years",
//     salary: "₹20L - ₹30L",
//     skills: ["Node.js", "TypeScript", "PostgreSQL", "AWS"],
//     description:
//       "We are seeking a Backend Engineer to build robust and scalable APIs that power our platform. You will work on complex data challenges and ensure our systems are highly available and performant.",
//     responsibilities: [
//       "Design, build, and maintain scalable APIs and microservices.",
//       "Optimize database queries and system architecture for performance.",
//       "Implement robust security measures and data protection protocols.",
//       "Collaborate with frontend engineers to define API contracts.",
//       "Participate in code reviews and architecture discussions.",
//     ],
//     requirements: [
//       "3+ years of backend development experience.",
//       "Strong proficiency in Node.js and TypeScript.",
//       "Experience with relational databases (PostgreSQL preferred) and ORMs.",
//       "Familiarity with cloud platforms (AWS, GCP) and containerization (Docker).",
//       "Understanding of RESTful API design and microservices architecture.",
//     ],
//     perks: [
//       "Remote-first culture",
//       "Top-tier health insurance",
//       "Flexible PTO policy",
//       "Annual retreat",
//       "Latest Apple equipment",
//     ],
//     postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
//     featured: true,
//   },
//   {
//     id: "job-5",
//     title: "Product Manager",
//     department: JobCategory.Product,
//     location: "Gurugram, HR (Hybrid)",
//     type: '"Day" | "Night" | "Flexible"',
//     experience: "4+ years",
//     salary: "₹18L - ₹25L",
//     skills: ["Agile", "User Research", "Roadmapping", "Data Analytics"],
//     description:
//       "As a Product Manager, you will lead cross-functional teams to deliver impactful features that solve real user problems. You will own the product roadmap for a key area of our platform.",
//     responsibilities: [
//       "Define and communicate the product vision and roadmap.",
//       "Gather and prioritize product and customer requirements.",
//       "Work closely with engineering, design, and marketing to deliver products.",
//       "Define key metrics to track product success and drive continuous improvement.",
//       "Conduct market research and competitive analysis.",
//     ],
//     requirements: [
//       "4+ years of product management experience in SaaS.",
//       "Strong analytical skills and data-driven decision making.",
//       "Excellent communication and stakeholder management skills.",
//       "Experience working in Agile/Scrum environments.",
//       "Technical background or strong technical understanding is a plus.",
//     ],
//     perks: [
//       "Hybrid working model",
//       "Private healthcare",
//       "Pension scheme",
//       "Cycle to work scheme",
//       "25 days annual leave",
//     ],
//     postedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
//     featured: true,
//   },
//   {
//     id: "job-6",
//     title: "Customer Success Operations",
//     department: JobCategory.Operations,
//     location: "Remote",
//     type: "Full-time",
//     experience: "2-4 years",
//     salary: "₹10L - ₹15L",
//     skills: ["Salesforce", "Zendesk", "Data Analysis", "Process Improvement"],
//     description:
//       "We are looking for a Customer Success Operations specialist to optimize our customer journey and improve our team's efficiency through data and process improvements.",
//     responsibilities: [
//       "Manage and optimize our CS tech stack (Zendesk, Salesforce, etc.).",
//       "Create and maintain dashboards to track key CS metrics (NPS, CSAT, Churn).",
//       "Develop and implement automated workflows to streamline processes.",
//       "Analyze customer data to identify trends and opportunities for improvement.",
//       "Enable the CS team with training and resources.",
//     ],
//     requirements: [
//       "2-4 years of experience in Customer Success Operations or a similar analytical role.",
//       "Proficiency with CRM and helpdesk tools.",
//       "Strong analytical skills with experience in Excel/Google Sheets and BI tools.",
//       "Excellent problem-solving skills and a process-oriented mindset.",
//       "Ability to work cross-functionally with Sales, Product, and Marketing.",
//     ],
//     perks: [
//       "Remote work flexibility",
//       "Health, dental, and vision insurance",
//       "401(k) plan",
//       "Generous paid time off",
//       "Professional development budget",
//     ],
//     postedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), // 14 days ago
//     featured: true,
//   },
//   {
//     id: "job-7",
//     title: "DevOps Engineer",
//     department: JobCategory.Engineering,
//     location: "Remote",
//     type: "Full-time",
//     experience: "4+ years",
//     salary: "₹25L - ₹40L",
//     skills: ["Kubernetes", "Terraform", "CI/CD", "AWS"],
//     description:
//       "Join our infrastructure team to build and maintain the cloud infrastructure that powers our platform. You will focus on reliability, scalability, and developer productivity.",
//     responsibilities: [
//       "Design, implement, and maintain our cloud infrastructure using IaC (Terraform).",
//       "Manage and optimize Kubernetes clusters.",
//       "Build and maintain robust CI/CD pipelines.",
//       "Implement comprehensive monitoring and alerting systems.",
//       "Ensure system security and compliance.",
//     ],
//     requirements: [
//       "4+ years of experience in DevOps or Site Reliability Engineering.",
//       "Strong expertise in AWS and Kubernetes.",
//       "Proficiency with Infrastructure as Code tools (e.g., Terraform).",
//       "Experience building CI/CD pipelines (e.g., GitHub Actions, GitLab CI).",
//       "Solid scripting skills (Python, Bash).",
//     ],
//     perks: [
//       "Fully remote work",
//       "Premium health benefits",
//       "Home office setup budget",
//       "Flexible working hours",
//       "Annual team offsites",
//     ],
//     postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
//     featured: false,
//   },
//   {
//     id: "job-8",
//     title: "Content Marketing Manager",
//     department: JobCategory.Marketing,
//     location: "Pune, MH (Hybrid)",
//     type: "Full-time",
//     experience: "3-5 years",
//     salary: "₹12L - ₹18L",
//     skills: ["Copywriting", "SEO", "Content Strategy", "Social Media"],
//     description:
//       "We're seeking a creative and strategic Content Marketing Manager to lead our content initiatives. You will create engaging content that drives brand awareness and lead generation.",
//     responsibilities: [
//       "Develop and execute a comprehensive content marketing strategy.",
//       "Create high-quality content including blog posts, whitepapers, case studies, and social media copy.",
//       "Manage the editorial calendar and content production workflow.",
//       "Optimize content for SEO to increase organic traffic.",
//       "Measure and report on the performance of content marketing efforts.",
//     ],
//     requirements: [
//       "3-5 years of experience in content marketing or B2B SaaS copywriting.",
//       "Exceptional writing and editing skills.",
//       "Strong understanding of SEO principles and content optimization.",
//       "Experience managing social media channels.",
//       "Creative thinker with a data-driven approach.",
//     ],
//     perks: [
//       "Hybrid work environment",
//       "Comprehensive health insurance",
//       "Unlimited PTO",
//       "Commuter benefits",
//       "Learning and development stipend",
//     ],
//     postedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), // 8 days ago
//     featured: false,
//   },
// ];

// export const MOCK_APPLICATIONS: Application[] = [
//   {
//     id: "app-1",
//     candidateId: "cand-12345",
//     jobId: "job-1",
//     jobTitle: "Senior Frontend Engineer",
//     name: "John Doe",
//     email: "john.doe@example.com",
//     status: "Submitted",
//     appliedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
//   },
//   {
//     id: "app-2",
//     candidateId: "cand-12345",
//     jobId: "job-4",
//     jobTitle: "Backend Engineer",
//     name: "John Doe",
//     email: "john.doe@example.com",
//     status: "Seen",
//     appliedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
//   },
//   {
//     id: "app-3",
//     candidateId: "cand-12345",
//     jobId: "job-2",
//     jobTitle: "Product Designer",
//     name: "John Doe",
//     email: "john.doe@example.com",
//     status: "Rejected",
//     appliedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), // 15 days ago
//   },
// ];
